billing/urls.py
from django.conf.urls import url
from billing.views import BillingView, clean_data, load_data

urlpatterns = [
    url(r'^$', BillingView.as_view(), name='billing'),
    url(r'^load_data$', load_data, name='load_data'),
    url(r'^clean_data$', clean_data, name='clean_data'),
]

gesnergy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from billing import urls as billing_urls
from lectures import urls as lectures_urls
from pricing import urls as pricing_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(billing_urls)),
    url(r'^lectures/', include(lectures_urls)),
    url(r'^pricing/', include(pricing_urls)),
]

pricing/urls.py
from django.conf.urls import url

from pricing.views import PricingListView, PricingView, PricingCreateView, PricingDeleteView, PricingUpdateView


urlpatterns = [
    url(r'^$', PricingListView.as_view(), name='pricing_list'),
    url(r'^new$', PricingCreateView.as_view(), name='pricing_create'),
    url(r'^(?P<pricing_id>[0-9]+)/$', PricingView.as_view(), name='pricing_detail'),
    url(r'^(?P<pricing_id>[0-9]+)/update$', PricingUpdateView.as_view(), name='pricing_update'),
    url(r'^(?P<pricing_id>[0-9]+)/delete$', PricingDeleteView.as_view(), name='pricing_delete'),
]

billing/models.py
from django.db import models
from django.urls import reverse


class Lecture(models.Model):
    day = models.DateField(unique=True)
    lecture = models.PositiveIntegerField()

    def get_absolute_url(self):
        return reverse('lecture_detail', kwargs={'lecture_id': self.pk})


class Pricing(models.Model):
    day = models.DateField(unique=True)
    price = models.FloatField()

    def get_absolute_url(self):
        return reverse('pricing_detail', kwargs={'pricing_id': self.pk})

pricing/models.py
from django.db import models
from django.urls import reverse


class Pricing(models.Model):
    day = models.DateField(unique=True)
    price = models.FloatField()

    def get_absolute_url(self):
        return reverse('pricing_detail', kwargs={'pricing_id': self.pk})

    def __str__(self):
        return str(round(self.price, 4))

    class Meta:
        ordering = ['-day']

pricing/forms.py
from django import forms
from pricing.models import Pricing


class PricingForm(forms.ModelForm):
    def is_valid(self):
        valid = super(PricingForm, self).is_valid()
        if not valid:
            return False

        if self.data["price"] < 0:
            return False

        return True

    class Meta:
        model = Pricing
        fields = '__all__'

pricing/views.py
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from pricing.models import Pricing
from pricing.tables import PricingTable
from django_tables2 import RequestConfig
from django.urls import reverse_lazy


class PricingCreateView(CreateView):
    model = Pricing
    fields = '__all__'


class PricingListView(ListView):
    model = Pricing

    def get_context_data(self, **kwargs):
        context = super(PricingListView, self).get_context_data(**kwargs)
        pricing = Pricing.objects.all()
        table = PricingTable(pricing)
        RequestConfig(self.request).configure(table)
        context['table'] = table
        context['pricing_list'] = pricing
        return context


class PricingView(DetailView):
    model = Pricing
    pk_url_kwarg = 'pricing_id'


class PricingDeleteView(DeleteView):
    model = Pricing
    pk_url_kwarg = 'pricing_id'
    success_url = reverse_lazy('pricing_list')


class PricingUpdateView(UpdateView):
    model = Pricing
    pk_url_kwarg = 'pricing_id'
    fields = '__all__'
    template_name_suffix = '_update_form'

pricing/templates/pricing/pricing_confirm_delete.html
{% extends "billing/billing.html" %}

{% block header %}Pricing{% endblock header %}


{% block menu %}
<li><a href="{% url 'billing' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
<li><a class="active-menu" href="{% url 'pricing_list' %}"><i class="fa fa-bolt"></i> Pricing</a></li>
<li><a href="{% url 'lecture_list' %}"><i class="fa fa-eye"></i> Lectures</a></li>
{% endblock menu %}


{% block breadcrumb %}
	<li><a href="{% url 'billing' %}">Dashboard</a></li>
	<li><a href="{% url 'pricing_list' %}">Pricing</a></li>
	<li class="active">Delete</li>
{% endblock breadcrumb %}

{% block main %}
	<form action="" method="post">{% csrf_token %}
	    <p>Are you sure you want to delete the pricing "{{object.day}} with price {{object.price}}"?</p>
	    <input class="btn btn-danger" type="submit" value="Cancel" onclick="window.history.back();"/>
	    <input class="btn btn-success" type="submit" value="Delete" />
	</form>
{% endblock main %}

pricing/templates/pricing/pricing_detail.html
{% extends "billing/billing.html" %}

{% block header %}Pricing{% endblock header %}


{% block menu %}
<li><a href="{% url 'billing' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
<li><a class="active-menu" href="{% url 'pricing_list' %}"><i class="fa fa-bolt"></i> Pricing</a></li>
<li><a href="{% url 'lecture_list' %}"><i class="fa fa-eye"></i> Lectures</a></li>
{% endblock menu %}


{% block breadcrumb %}
	<li><a href="{% url 'billing' %}">Dashboard</a></li>
	<li><a href="{% url 'pricing_list' %}">Pricing</a></li>
	<li class="active">Details</li>
{% endblock breadcrumb %}

{% block main %}
	<p><strong>Day: </strong> {{object.day}}</p>
	<p><strong>Price: </strong> {{object.price}} €</p>
	<input class="btn btn-danger" type="submit" value="Cancel" onclick="window.history.back();"/>
{% endblock main %}

pricing/templates/pricing/pricing_form.html
{% extends "billing/billing.html" %}

{% block header %}Pricing{% endblock header %}


{% block menu %}
<li><a href="{% url 'billing' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
<li><a class="active-menu" href="{% url 'pricing_list' %}"><i class="fa fa-bolt"></i> Pricing</a></li>
<li><a href="{% url 'lecture_list' %}"><i class="fa fa-eye"></i> Lectures</a></li>
{% endblock menu %}


{% block breadcrumb %}
	<li><a href="{% url 'billing' %}">Dashboard</a></li>
	<li><a href="{% url 'pricing_list' %}">Pricing</a></li>
	<li class="active">Add</li>
{% endblock breadcrumb %}

{% block main %}
	<form action="" method="post">
		{% csrf_token %}
    	{{ form.as_p }}
    	<input type="submit" value="Save" />
	</form>
{% endblock main %}

pricing/templates/pricing/pricing_list.html
{% extends "billing/billing.html" %}
{% load django_tables2 %}

{% block header %}Pricing{% endblock header %}

{% block menu %}
	<li><a href="{% url 'billing' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
	<li><a class="active-menu" href="{% url 'pricing_list' %}"><i class="fa fa-bolt"></i> Pricing</a></li>
	<li><a href="{% url 'lecture_list' %}"><i class="fa fa-eye"></i> Lectures</a></li>
{% endblock menu %}

{% block breadcrumb %}
	<li><a href="{% url 'billing' %}">Dashboard</a></li>
	<li class="active">Pricing</li>
{% endblock breadcrumb %}

{% block main %}
	<a href="{% url 'pricing_create' %}"><button type="button" class="btn btn-default add"><i class="fa fa-plus" aria-hidden="true"></i> Add</button></a>
	{% render_table table "billing/table.html" %}	
{% endblock main %}

pricing/templates/pricing/pricing_update_form.html
{% extends "billing/billing.html" %}

{% block header %}Pricing{% endblock header %}


{% block menu %}
<li><a href="{% url 'billing' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
<li><a class="active-menu" href="{% url 'pricing_list' %}"><i class="fa fa-bolt"></i> Pricing</a></li>
<li><a href="{% url 'lecture_list' %}"><i class="fa fa-eye"></i> Lectures</a></li>
{% endblock menu %}


{% block breadcrumb %}
	<li><a href="{% url 'billing' %}">Dashboard</a></li>
	<li><a href="{% url 'pricing_list' %}">Pricing</a></li>
	<li class="active">Update</li>
{% endblock breadcrumb %}

{% block main %}
	<form action="" method="post">
		{% csrf_token %}
    	{{ form.as_p }}
		<input class="btn btn-danger" type="submit" value="Cancel" onclick="window.history.back();"/>
    	<input class="btn btn-success" type="submit" value="Update" />
	</form>
{% endblock main %}