billing/urls.py
from django.conf.urls import url
from billing.views import BillingView, clean_data, load_data

urlpatterns = [
    url(r'^$', BillingView.as_view(), name='billing'),
    url(r'^load_data$', load_data, name='load_data'),
    url(r'^clean_data$', clean_data, name='clean_data'),
]

gesnergy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from billing import urls as billing_urls
from lectures import urls as lectures_urls
from pricing import urls as pricing_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(billing_urls)),
    url(r'^lectures/', include(lectures_urls)),
    url(r'^pricing/', include(pricing_urls)),
]

lectures/urls.py
from django.conf.urls import url
from lectures.views import LectureListView, LectureView, LectureCreateView, LectureDeleteView, LectureUpdateView

urlpatterns = [
    url(r'^$', LectureListView.as_view(), name='lecture_list'),
    url(r'^new$', LectureCreateView.as_view(), name='lecture_create'),
    url(r'^(?P<lecture_id>[0-9]+)/$', LectureView.as_view(), name='lecture_detail'),
    url(r'^(?P<lecture_id>[0-9]+)/update$', LectureUpdateView.as_view(), name='lecture_update'),
    url(r'^(?P<lecture_id>[0-9]+)/delete$', LectureDeleteView.as_view(), name='lecture_delete'),
]

billing/models.py
from django.db import models
from django.urls import reverse


class Lecture(models.Model):
    day = models.DateField(unique=True)
    lecture = models.PositiveIntegerField()

    def get_absolute_url(self):
        return reverse('lecture_detail', kwargs={'lecture_id': self.pk})


class Pricing(models.Model):
    day = models.DateField(unique=True)
    price = models.FloatField()

    def get_absolute_url(self):
        return reverse('pricing_detail', kwargs={'pricing_id': self.pk})

lectures/models.py
from django.db import models
from django.urls import reverse


class Lecture(models.Model):
    day = models.DateField(unique=True)
    lecture = models.PositiveIntegerField()

    def get_absolute_url(self):
        return reverse('lecture_detail', kwargs={'lecture_id': self.pk})

    def __str__(self):
        return str(self.lecture)

    class Meta:
        ordering = ['-day']

lectures/forms.py
from django import forms
from lectures.models import Lecture


class LectureForm(forms.ModelForm):
    class Meta:
        model = Lecture
        fields = '__all__'

    def is_valid(self):
        valid = super(LectureForm, self).is_valid()
        if not valid:
            return False
        if Lecture.objects.count() > 0:
            if self.data["lecture"] < Lecture.objects.last().lecture:
                return False

        return True

lectures/views.py
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView

from lectures.models import Lecture
from lectures.tables import LectureTable

from django_tables2 import RequestConfig
from django.urls import reverse_lazy


class LectureListView(ListView):
    model = Lecture

    def get_context_data(self, **kwargs):
        context = super(LectureListView, self).get_context_data(**kwargs)
        lectures = Lecture.objects.all()
        table = LectureTable(lectures)
        RequestConfig(self.request).configure(table)
        context['table'] = table
        context['lectures_list'] = lectures
        return context


class LectureCreateView(CreateView):
    model = Lecture
    fields = '__all__'


class LectureView(DetailView):
    model = Lecture
    pk_url_kwarg = 'lecture_id'


class LectureDeleteView(DeleteView):
    model = Lecture
    pk_url_kwarg = 'lecture_id'
    success_url = reverse_lazy('lecture_list')


class LectureUpdateView(UpdateView):
    model = Lecture
    pk_url_kwarg = 'lecture_id'
    fields = '__all__'
    template_name_suffix = '_update_form'

lectures/templates/lectures/lecture_confirm_delete.html
{% extends "billing/billing.html" %}

{% block header %}Lectures{% endblock header %}

{% block menu %}
	<li><a href="{% url 'billing' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
	<li><a href="{% url 'pricing_list' %}"><i class="fa fa-bolt"></i> Pricing</a></li>
	<li><a class="active-menu" href="{% url 'lecture_list' %}"><i class="fa fa-calendar"></i> Lectures</a></li>
{% endblock menu %}


{% block breadcrumb %}
	<li><a href="{% url 'billing' %}">Dashboard</a></li>
	<li><a href="{% url 'lecture_list' %}">Lectures</a></li>
	<li class="active">Delete</li>
{% endblock breadcrumb %}

{% block main %}
	<form action="" method="post">{% csrf_token %}
    	<p>Are you sure you want to delete the lecture of day "{{object.day}}" with lecture {{object.lecture}}"?</p>
	    <input class="btn btn-danger" type="submit" value="Cancel" onclick="window.history.back();"/>
	    <input class="btn btn-success" type="submit" value="Delete" />
	</form>
{% endblock main %}

lectures/templates/lectures/lecture_detail.html
{% extends "billing/billing.html" %}

{% block header %}Lectures{% endblock header %}

{% block menu %}
	<li><a href="{% url 'billing' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
	<li><a href="{% url 'pricing_list' %}"><i class="fa fa-bolt"></i> Pricing</a></li>
	<li><a class="active-menu" href="{% url 'lecture_list' %}"><i class="fa fa-calendar"></i> Lectures</a></li>
{% endblock menu %}


{% block breadcrumb %}
	<li><a href="{% url 'billing' %}">Dashboard</a></li>
	<li><a href="{% url 'lecture_list' %}">Lectures</a></li>
	<li class="active">Details</li>
{% endblock breadcrumb %}

{% block main %}
	<p><strong>Day: </strong> {{object.day}}</p>
	<p><strong>Lecture: </strong> {{object.lecture}}kw</p>
	<input class="btn btn-danger" type="submit" value="Cancel" onclick="window.history.back();"/>
{% endblock main %}

lectures/templates/lectures/lecture_form.html
{% extends "billing/billing.html" %}

{% block header %}Lectures{% endblock header %}

{% block menu %}
	<li><a href="{% url 'billing' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
	<li><a href="{% url 'pricing_list' %}"><i class="fa fa-bolt"></i> Pricing</a></li>
	<li><a class="active-menu" href="{% url 'lecture_list' %}"><i class="fa fa-calendar"></i> Lectures</a></li>
{% endblock menu %}


{% block breadcrumb %}
	<li><a href="{% url 'billing' %}">Dashboard</a></li>
	<li><a href="{% url 'lecture_list' %}">Lectures</a></li>
	<li class="active">Add</li>
{% endblock breadcrumb %}

{% block main %}
	<form action="" method="post">
		{% csrf_token %}
    	{{ form.as_p }}
    	<input type="submit" value="Save" />
	</form>
{% endblock main %}

lectures/templates/lectures/lecture_list.html
{% extends "billing/billing.html" %}

{% load django_tables2 %}

{% block header %}Lectures{% endblock header %}

{% block menu %}
	<li><a href="{% url 'billing' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
	<li><a href="{% url 'pricing_list' %}"><i class="fa fa-bolt"></i> Pricing</a></li>
	<li><a class="active-menu" href="{% url 'lecture_list' %}"><i class="fa fa-calendar"></i> Lectures</a></li>
{% endblock menu %}

{% block breadcrumb %}
	<li><a href="{% url 'billing' %}">Dashboard</a></li>
	<li class="active">Lectures</li>
{% endblock breadcrumb %}

{% block main %}
	<a href="{% url 'lecture_create' %}"><button type="button" class="btn btn-default add"><i class="fa fa-plus" aria-hidden="true"></i> Add</button></a>
	{% render_table table "billing/table.html" %}
{% endblock main %}

lectures/templates/lectures/lecture_update_form.html
{% extends "billing/billing.html" %}

{% block header %}Lectures{% endblock header %}

{% block menu %}
	<li><a href="{% url 'billing' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
	<li><a href="{% url 'pricing_list' %}"><i class="fa fa-bolt"></i> Pricing</a></li>
	<li><a class="active-menu" href="{% url 'lecture_list' %}"><i class="fa fa-calendar"></i> Lectures</a></li>
{% endblock menu %}


{% block breadcrumb %}
	<li><a href="{% url 'billing' %}">Dashboard</a></li>
	<li><a href="{% url 'lecture_list' %}">Lectures</a></li>
	<li class="active">Update</li>
{% endblock breadcrumb %}

{% block main %}
	<form action="" method="post">
		{% csrf_token %}
    	{{ form.as_p }}
		<input class="btn btn-danger" type="submit" value="Cancel" onclick="window.history.back();"/>
    	<input class="btn btn-success" type="submit" value="Update" />
	</form>
{% endblock main %}